language: go
go: 
 - 1.4
 - release
 - tip

before_script:
  - go get github.com/benbjohnson/ego/cmd/ego
  - mysql -e 'create database scaffold_test;'

script:
 - export TEST_DATABASE_URL=travis:@tcp\(127.0.0.1:3306\)/scaffold_test
 - ./script/test

install:
  - ./script/build

