name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Scaffold
        run: ./script/build.sh

      - name: Test Scaffold
        run: ./script/test.sh

